### ISSUE TITLE
Setup auth.dwyl.com subdomain

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#177]
+ [x] Setup auth.dwyl.com subdomain on CloudFlare and redirect it to https://authprod.fly.dev/

Relates to #172 / #173

**Comment by nelsonic** [comment]
Configured the subdomain on Cloudflare:
![auth dwyl com-cloudflare-dns-config](https://user-images.githubusercontent.com/194400/152762809-8e32516e-5b21-45cb-8de1-4e1df6863ef6.png)

Looks good: https://auth.dwyl.com/
![image](https://user-images.githubusercontent.com/194400/152762916-b198343f-7a51-40b5-a128-67cbf4cc32ec.png)

But not yet fully working. 
![image](https://user-images.githubusercontent.com/194400/152762984-afa9f1dd-24a7-471d-b2eb-b805acaaab7e.png)

Log:
![image](https://user-images.githubusercontent.com/194400/152763455-72298deb-dc60-4afe-9ed2-f678b792a5f3.png)

```
2022-02-07T09:39:10Z app[ba4a82f7] cdg [info]Server: auth.dwyl.com:80 (http)
2022-02-07T09:39:10Z app[ba4a82f7] cdg [info]Request: GET /auth/github/callback?code=code&state=https%3A%2F%2Fauth.dwyl.com%2Fprofile%3Fauth_client_id=id
2022-02-07T09:39:10Z app[ba4a82f7] cdg [info]** (exit) an exception was raised:
2022-02-07T09:39:10Z app[ba4a82f7] cdg [info]    ** (UndefinedFunctionError) function Mix.env/0 is undefined (module Mix is not available)
2022-02-07T09:39:10Z app[ba4a82f7] cdg [info]        Mix.env()
2022-02-07T09:39:10Z app[ba4a82f7] cdg [info]        (elixir_auth_github 1.6.0) lib/elixir_auth_github.ex:18: ElixirAuthGithub.inject_poison/0
2022-02-07T09:39:10Z app[ba4a82f7] cdg [info]        (elixir_auth_github 1.6.0) lib/elixir_auth_github.ex:65: ElixirAuthGithub.github_auth/1
2022-02-07T09:39:10Z app[ba4a82f7] cdg [info]        (auth 1.6.5) lib/auth_web/controllers/auth_controller.ex:136: AuthWeb.AuthController.github_handler/2
2022-02-07T09:39:10Z app[ba4a82f7] cdg [info]        (auth 1.6.5) lib/auth_web/controllers/auth_controller.ex:1: AuthWeb.AuthController.action/2
2022-02-07T09:39:10Z app[ba4a82f7] cdg [info]        (auth 1.6.5) lib/auth_web/controllers/auth_controller.ex:1: AuthWeb.AuthController.phoenix_controller_pipeline/2
2022-02-07T09:39:10Z app[ba4a82f7] cdg [info]        (phoenix 1.6.5) lib/phoenix/router.ex:355: Phoenix.Router.__call__/2
2022-02-07T09:39:10Z app[ba4a82f7] cdg [info]        (auth 1.6.5) lib/auth_web/endpoint.ex:1: AuthWeb.Endpoint.plug_builder_call/2
```

`GOTO` GitHub Auth `Mix.env()` Issue: https://github.com/dwyl/elixir-auth-github/issues/51
Cloudflare setup is complete. ✅
