### ISSUE TITLE
Integrate Email Service via /api/send

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#41]
We have finished building the separate email service https://github.com/dwyl/auth/issues/39 https://github.com/dwyl/email ✅ 
Now we need to _use_ that service to send _welcome_ emails when people authenticate.

+ [x] use `/api/send` to send welcome email following the instructions in: 
https://github.com/dwyl/email#sending-email

In the context of our diagram, we are performing **Step 3**:
![dwyl-app-services-diagram](https://user-images.githubusercontent.com/194400/77526292-41628180-6e82-11ea-8044-dacbc57ba895.png)

**Comment by nelsonic** [comment]
Annoying error when attempting to use a JWT in `Authorization` header:
```
  1) test AuthMvp.Email send/1 an email (AuthMvp.EmailTest)
     test/auth_mvp/email_test.exs:5
     ** (ArgumentError) argument error
     code: res = AuthMvp.Email.send(params)
     stacktrace:
       :erlang.iolist_to_binary([Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJKb2tlbiIsImVtYWlsIjoic3VjY2Vzc0BzaW11bGF0b3IuYW1hem9uc2VzLmNvbSIsImV4cCI6MTYxNjg2MDcyOSwiaWF0IjoxNTg1MzIzNzI5LCJpc3MiOiJKb2tlbiIsImp0aSI6IjJvMDM3MjJhYjA0bmg4bGppazAwMDBmMSIsIm5hbWUiOiJTdXBlciBTdWNjZXNzZnVsIiwibmJmIjoxNTg1MzIzNzI5LCJ0ZW1wbGF0ZSI6IndlbGNvbWUifQ.iVjxMsyCTmaem_N4TH3YiXOasTPIGTHR0XOpnlEK2qc", "Content-Type": "application/json"])
       (hackney 1.15.2) /Users/n/code/auth-mvp/deps/hackney/src/hackney_request.erl:348: :hackney_request.handle_body/4
       (hackney 1.15.2) /Users/n/code/auth-mvp/deps/hackney/src/hackney_request.erl:83: :hackney_request.perform/2
       (hackney 1.15.2) /Users/n/code/auth-mvp/deps/hackney/src/hackney.erl:376: :hackney.send_request/2
       (httpoison 1.6.2) lib/httpoison/base.ex:796: HTTPoison.Base.request/6
       (auth_mvp 0.1.0) lib/auth_mvp/email.ex:14: AuthMvp.Email.send/1
       test/auth_mvp/email_test.exs:12: (test)
```

**Comment by nelsonic** [comment]
Figured out the hackney error. It was because of an incorrect ordering of parameters. 
The correct code is:
https://github.com/dwyl/auth-mvp/blob/556f1b186c5399a42004ff047e4f5a8de08ee069/lib/auth_mvp/email.ex#L31

PR https://github.com/dwyl/auth-mvp/pull/17 created. ✅

**Comment by nelsonic** [comment]
Included in https://github.com/dwyl/auth/pull/43 💌 ✅
