### ISSUE TITLE
no function clause matching in Plug.CSRFProtection.get_csrf_token_for/1

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#61]
Trying to create the login form and getting the following error:

![image](https://user-images.githubusercontent.com/194400/80819765-87231000-8bcd-11ea-99e1-b0c3acc2fe6d.png)

```sh
[error] #PID<0.740.0> running AuthWeb.Endpoint (connection #PID<0.739.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Plug.CSRFProtection.get_csrf_token_for/1
        (plug 1.10.0) lib/plug/csrf_protection.ex:237: Plug.CSRFProtection.get_csrf_token_for(#Function<0.88702904/1 in AuthWeb.PageView."index.html"/1>)
        (phoenix_html 2.14.1) lib/phoenix_html/tag.ex:241: Phoenix.HTML.Tag.csrf_token_tag/3
        (phoenix_html 2.14.1) lib/phoenix_html/tag.ex:197: Phoenix.HTML.Tag.form_tag/2
        (phoenix_html 2.14.1) lib/phoenix_html/form.ex:263: Phoenix.HTML.Safe.Phoenix.HTML.Form.to_iodata/1
        (auth 1.2.1) lib/auth_web/templates/page/index.html.eex:50: AuthWeb.PageView."index.html"/1
        (auth 1.2.1) lib/auth_web/templates/layout/app.html.eex:19: AuthWeb.LayoutView."app.html"/1
        (phoenix 1.4.17) lib/phoenix/view.ex:410: Phoenix.View.render_to_iodata/3
        (phoenix 1.4.17) lib/phoenix/controller.ex:776: Phoenix.Controller.__put_render__/5
        (phoenix 1.4.17) lib/phoenix/controller.ex:792: Phoenix.Controller.instrument_render_and_send/4
        (auth 1.2.1) lib/auth_web/controllers/page_controller.ex:1: AuthWeb.PageController.action/2
        (auth 1.2.1) lib/auth_web/controllers/page_controller.ex:1: AuthWeb.PageController.phoenix_controller_pipeline/2
        (phoenix 1.4.17) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
        (auth 1.2.1) lib/auth_web/endpoint.ex:1: AuthWeb.Endpoint.plug_builder_call/2
        (auth 1.2.1) lib/plug/debugger.ex:132: AuthWeb.Endpoint."call (overridable 3)"/2
        (auth 1.2.1) lib/auth_web/endpoint.ex:1: AuthWeb.Endpoint.call/2
        (phoenix 1.4.17) lib/phoenix/endpoint/cowboy2_handler.ex:42: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.7.0) /Users/n/code/auth/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy 2.7.0) /Users/n/code/auth/deps/cowboy/src/cowboy_stream_h.erl:320: :cowboy_stream_h.execute/3
        (cowboy 2.7.0) /Users/n/code/auth/deps/cowboy/src/cowboy_stream_h.erl:302: :cowboy_stream_h.request_process/3
        (stdlib 3.11.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

Going to keep debugging it ... just opening this issue to capture the eventual solution ... 🔍

**Comment by nelsonic** [comment]
Ok this is was one of the more cryptic errors I've seen in Elixir/Phoenix. 
After going on a wild goose chase reading https://hexdocs.pm/plug/Plug.CSRFProtection.html ...
I discovered by dissecting existing _working_ forms that it had absolutely _nothing_ to do with CSRFProtection. It was because my form did not have an `@action` property!

This failed:
```elixir
<%= form_for @changeset,  fn f -> %>
```
Whereas this works:
```elixir
<%= form_for @changeset, @action,  fn f -> %>
```

But I had to setup the `action` prop in the controller before rendering the form:

```elixir
conn = assign(conn, :action, Routes.auth_path(conn, :login_register_handler))
```
Now it works as expected:
![image](https://user-images.githubusercontent.com/194400/80843031-1db9f600-8bfb-11ea-91b2-5bf9268b9682.png)

**Comment by ryan-senn** [comment]
Seeing as this is the first result in google search for that particular error, I'll add another scenario: using a <.simple_form> core_component, I misspelled the <:actions> slot as <:action> (note missing trailing s). Not exactly the error you'd expect.
