### ISSUE TITLE
Tests failing after adding many_to_many relationship to People via people_roles

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#89]
```
  1) test google_handler/2 show welcome (state=nil) > handler/3 (AuthWeb.AuthControllerTest)
     test/auth_web/controllers/auth_controller_test.exs:119
     ** (RuntimeError) cannot encode association :roles from Auth.Person to JSON because the association was not loaded.

     You can either preload the association:

         Repo.preload(Auth.Person, :roles)

     Or choose to not encode the association when converting the struct to JSON by explicitly listing the JSON fields in your schema:

         defmodule Auth.Person do
           # ...

           @derive {Jason.Encoder, only: [:name, :title, ...]}
           schema ... do

     code: conn = AuthPlug.create_jwt_session(conn, person)
     stacktrace:
       (ecto 3.4.5) lib/ecto/json.ex:4: Jason.Encoder.Ecto.Association.NotLoaded.encode/2
       (jason 1.2.1) lib/encode.ex:182: Jason.Encode.map_naive_loop/3
       (jason 1.2.1) lib/encode.ex:183: Jason.Encode.map_naive_loop/3
       (jason 1.2.1) lib/encode.ex:173: Jason.Encode.map_naive/3
       (jason 1.2.1) lib/encode.ex:35: Jason.Encode.encode/2
       (jason 1.2.1) lib/jason.ex:148: Jason.encode!/2
       (jose 1.10.1) src/jwt/jose_jwt.erl:89: :jose_jwt.to_binary/1
       (jose 1.10.1) src/jwt/jose_jwt.erl:172: :jose_jwt.sign/3
       (joken 2.2.0) lib/joken/signer.ex:119: Joken.Signer.sign/2
       (joken 2.2.0) lib/joken.ex:365: Joken.encode_and_sign/3
       (auth_plug 1.2.0) lib/token.ex:70: AuthPlug.Token.generate_jwt!/2
       (auth_plug 1.2.0) lib/auth_plug.ex:108: AuthPlug.create_jwt_session/2
       test/auth_web/controllers/auth_controller_test.exs:129: (test)
```

It should be fairly straightforward to fix. ⏳

**Comment by nelsonic** [comment]
Figured it out with help from @marinho10's post on Ecto Many-to-Many relationships: 🙌 
https://medium.com/coletiv-stories/ecto-elixir-many-to-many-relationships-66403933f8c1

And:
+ https://thoughtbot.com/blog/preloading-nested-associations-with-ecto
+ https://elixirforum.com/t/trouble-with-many-to-many-association/4540
+ https://hexdocs.pm/ecto/Ecto.Query.html
